<?php

namespace ContainerDDCV5rv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_FBeg586Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.fBeg586' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Application/GetItem/GetItemHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Service/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Service/VendingMachine.php';

        return $container->privates['.messenger.handler_descriptor.fBeg586'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Application\GetItem\GetItemHandler(($container->privates['App\\Domain\\Service\\VendingMachineProcessor'] ?? ($container->privates['App\\Domain\\Service\\VendingMachineProcessor'] = new \App\Domain\Service\VendingMachineProcessor()))), []);
    }
}
